name: CD

on:
  workflow_dispatch:
    inputs:
      version:
        description: A SemVer for the release
        default: ""
        required: true
        type: string

defaults:
  run:
    shell: pwsh

jobs:
  ci:
    name: Run CI
    uses: ./.github/workflows/ci.yml
    with:
      version: ${{ inputs.version }}
      branch_name: main
    secrets: inherit

  publish:
    name: Publish to npm

    needs:
      - ci

    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci

      - name: Download Build
        uses: actions/download-artifact@v3
        with:
          name: Build
          path: ./dist

      - name: Publish
        run: npx nx run-many --target publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}

  create-release:
    name: Create GitHub Release

    needs:
      - publish

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Download Build
        uses: actions/download-artifact@v3
        with:
          name: Build
          path: ./dist

      - name: Pack assets
        run: npx nx run-many --target pack

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ inputs.version }}
          generate_release_notes: true
          files: dist/**.tgz
          body: |
            # Release v${{ inputs.version }}

            Download from [npm](https://www.npmjs.com/package/license-cop/v/${{ inputs.version }}): `npm install license-cop@${{ inputs.version }} --save-dev`
