name: Migrate NX

on:
  schedule:
    - cron: 57 17 * * 3
  workflow_dispatch:

env:
  NODE_VERSION: 18

defaults:
  run:
    shell: pwsh

jobs:
  prepare:
    name: Prepare Nx Branch
    uses: tobysmith568/actions/.github/workflows/nx-preparation.yml@main
    with:
      node_version: 18
    permissions:
      actions: read
      contents: read
      security-events: write

  ci:
    name: Run CI
    needs:
      - prepare
    uses: ./.github/workflows/ci.yml
    with:
      version: ${{ inputs.version }}
      branch_name: ${{ needs.prepare.outputs.branch_name }}
    secrets: inherit
#  merge:
#    name: Merge Nx Branch
#    needs:
#      - ci
#    if: ${{
#    uses: tobysmith568/actions/.github/workflows/nx-merge.yml@main
