name: Migrate NX

on:
  schedule:
    - cron: 57 17 * * 3
  workflow_dispatch:

env:
  NODE_VERSION: 18

defaults:
  run:
    shell: pwsh

jobs:
  prepare:
    name: Prepare Nx Branch
    uses: tobysmith568/actions/.github/workflows/nx-preparation.yml@main
    with:
      node_version: 18
    permissions:
      contents: write

  ci:
    name: Run CI
    needs:
      - prepare
    if: ${{ needs.prepare.outputs.should_continue }}
    uses: ./.github/workflows/ci.yml
    with:
      branch_name: ${{ needs.prepare.outputs.branch_name }}-broken # Broken the branch name to help the development of the nx shared steps
      continue_on_error: true
    secrets: inherit

  pr:
    name: Create pull request
    needs:
      - ci
    if: ${{ always() && needs.ci.result == 'failure' }}
    uses: tobysmith568/actions/.github/workflows/nx-pr.yml@main
    with:
      node_version: 18
    permissions:
      pull-requests: write

  merge:
    name: Merge Nx Branch
    needs:
      - ci
    if: ${{ always() && needs.ci.result == 'success' }}
    uses: tobysmith568/actions/.github/workflows/nx-merge.yml@main
    permissions:
      contents: write
